name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Unit testing
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm test
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Violet est la couleur du papers, le commercant ne rend pas la monnaie
            - Casper
          draft: false
          prerelease: false
